# docker-compose.yaml
version: '3.9'
services:
  web:
    image: docker:dind
    container_name: deployment
    restart: always
    privileged: true
    ports:
      - 8090:8080

  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8098:8081"

  jenkins:
    restart: on-failure:10
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - 8099:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

  db-sonarqube:
    image: 'postgres:10.9'
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=dockersonar
      - POSTGRES_DB=sonarqube
      - JVM_OPTS=-Xmx500m
    volumes:
      - './postgresql_home:/var/lib/postgresql/data'

  sonarqube:
    image: sonarqube:8.9.9-community
    restart: always
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonarqube:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=dockersonar
      - JVM_OPTS=-Xmx2g
    stop_grace_period: 5m
    depends_on:
      - "db-sonarqube"
    volumes:
      - ./sonarqube_home:/opt/sonarqube/data
    ports:
      - "8100:9000"

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea_home:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
 

volumes:
  nexus-data: {} 
networks:
  gitea:
    external: false
