# docker-compose.yaml
version: '3.9'
services:
  web:
    image: docker:dind
    container_name: deployment
    restart: always
    privileged: true
    ports:
      - 8090:8080

  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8098:8081"

  jenkins:
    restart: on-failure:10
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - 8099:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea_home:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
 

volumes:
  nexus-data: {} 
networks:
  gitea:
    external: false
